
from django.urls import path, include
from . import views
from .import HodViews, StaffViews, EmployeeViews


urlpatterns = [
    path('', views.loginPage, name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', HodViews.admin_home, name="admin_home"),
    path('add_staff/', HodViews.add_staff, name="add_staff"),
    path('add_staff_save/', HodViews.add_staff_save, name="add_staff_save"),
    path('manage_staff/', HodViews.manage_staff, name="manage_staff"),
    path('edit_staff/<staff_id>/', HodViews.edit_staff, name="edit_staff"),
    path('edit_staff_save/', HodViews.edit_staff_save, name="edit_staff_save"),
    path('delete_staff/<staff_id>/', HodViews.delete_staff, name="delete_staff"),
    path('add_course/', HodViews.add_course, name="add_course"),
    path('add_course_save/', HodViews.add_course_save, name="add_course_save"),
    path('manage_course/', HodViews.manage_course, name="manage_course"),
    path('edit_course/<course_id>/', HodViews.edit_course, name="edit_course"),
    path('edit_course_save/', HodViews.edit_course_save, name="edit_course_save"),
    path('delete_course/<course_id>/', HodViews.delete_course, name="delete_course"),
    path('manage_session/', HodViews.manage_session, name="manage_session"),
    path('add_session/', HodViews.add_session, name="add_session"),
    path('add_session_save/', HodViews.add_session_save, name="add_session_save"),
    path('edit_session/<session_id>', HodViews.edit_session, name="edit_session"),
    path('edit_session_save/', HodViews.edit_session_save, name="edit_session_save"),
    path('delete_session/<session_id>/', HodViews.delete_session, name="delete_session"),
    path('add_employee/', HodViews.add_employee, name="add_employee"),
    path('add_employee_save/', HodViews.add_employee_save, name="add_employee_save"),
    path('edit_employee/<employee_id>', HodViews.edit_employee, name="edit_employee"),
    path('edit_employee_save/', HodViews.edit_employee_save, name="edit_employee_save"),
    path('manage_employee/', HodViews.manage_employee, name="manage_employee"),
    path('delete_employee/<employee_id>/', HodViews.delete_employee, name="delete_employee"),
    path('add_subject/', HodViews.add_subject, name="add_subject"),
    path('add_subject_save/', HodViews.add_subject_save, name="add_subject_save"),
    path('manage_subject/', HodViews.manage_subject, name="manage_subject"),
    path('edit_subject/<subject_id>/', HodViews.edit_subject, name="edit_subject"),
    path('edit_subject_save/', HodViews.edit_subject_save, name="edit_subject_save"),
    path('delete_subject/<subject_id>/', HodViews.delete_subject, name="delete_subject"),
    path('check_email_exist/', HodViews.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', HodViews.check_username_exist, name="check_username_exist"),
    path('employee_feedback_message/', HodViews.employee_feedback_message, name="employee_feedback_message"),
    path('employee_feedback_message_reply/', HodViews.employee_feedback_message_reply, name="employee_feedback_message_reply"),
    path('staff_feedback_message/', HodViews.staff_feedback_message, name="staff_feedback_message"),
    path('staff_feedback_message_reply/', HodViews.staff_feedback_message_reply, name="staff_feedback_message_reply"),
    path('employee_leave_view/', HodViews.employee_leave_view, name="employee_leave_view"),
    path('employee_leave_approve/<leave_id>/', HodViews.employee_leave_approve, name="employee_leave_approve"),
    path('employee_leave_reject/<leave_id>/', HodViews.employee_leave_reject, name="employee_leave_reject"),
    path('staff_leave_view/', HodViews.staff_leave_view, name="staff_leave_view"),
    path('staff_leave_approve/<leave_id>/', HodViews.staff_leave_approve, name="staff_leave_approve"),
    path('staff_leave_reject/<leave_id>/', HodViews.staff_leave_reject, name="staff_leave_reject"),
    path('admin_view_attendance/', HodViews.admin_view_attendance, name="admin_view_attendance"),
    path('admin_get_attendance_dates/', HodViews.admin_get_attendance_dates, name="admin_get_attendance_dates"),
    path('admin_get_attendance_employee/', HodViews.admin_get_attendance_employee, name="admin_get_attendance_employee"),
    path('admin_profile/', HodViews.admin_profile, name="admin_profile"),
    path('admin_profile_update/', HodViews.admin_profile_update, name="admin_profile_update"),
    


    # URLS for Staff
    path('staff_home/', StaffViews.staff_home, name="staff_home"),
    path('staff_take_attendance/', StaffViews.staff_take_attendance, name="staff_take_attendance"),
    path('get_employees/', StaffViews.get_employees, name="get_employees"),
    path('save_attendance_data/', StaffViews.save_attendance_data, name="save_attendance_data"),
    path('staff_update_attendance/', StaffViews.staff_update_attendance, name="staff_update_attendance"),
    path('get_attendance_dates/', StaffViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_employee/', StaffViews.get_attendance_employee, name="get_attendance_employee"),
    path('update_attendance_data/', StaffViews.update_attendance_data, name="update_attendance_data"),
    path('staff_apply_leave/', StaffViews.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save/', StaffViews.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback/', StaffViews.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save/', StaffViews.staff_feedback_save, name="staff_feedback_save"),
    path('staff_profile/', StaffViews.staff_profile, name="staff_profile"),
    path('staff_profile_update/', StaffViews.staff_profile_update, name="staff_profile_update"),
    path('staff_add_result/', StaffViews.staff_add_result, name="staff_add_result"),
    path('staff_add_result_save/', StaffViews.staff_add_result_save, name="staff_add_result_save"),

    # URSL for employee
    path('employee_home/', EmployeeViews.employee_home, name="employee_home"),
    path('employee_view_attendance/', EmployeeViews.employee_view_attendance, name="employee_view_attendance"),
    path('employee_view_attendance_post/', EmployeeViews.employee_view_attendance_post, name="employee_view_attendance_post"),
    path('employee_apply_leave/', EmployeeViews.employee_apply_leave, name="employee_apply_leave"),
    path('employee_apply_leave_save/', EmployeeViews.employee_apply_leave_save, name="employee_apply_leave_save"),
    path('employee_feedback/', EmployeeViews.employee_feedback, name="employee_feedback"),
    path('employee_feedback_save/', EmployeeViews.employee_feedback_save, name="employee_feedback_save"),
    path('employee_profile/', EmployeeViews.employee_profile, name="employee_profile"),
    path('employee_profile_update/', EmployeeViews.employee_profile_update, name="employee_profile_update"),
    path('employee_view_result/', EmployeeViews.employee_view_result, name="employee_view_result"),
]
